require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true


platform :ios, '12.4'
# install! 'cocoapods', :deterministic_uuids => false

target 'app' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
